// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzonvhzmyksxccffrqup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6b252aHpteWtzeGNjZmZycXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NjI5MDgsImV4cCI6MjA2MTEzODkwOH0.WxzDM7fc2T8gfEQJJss-tWIPucX66l-qJpvydrl1aAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);